version: '3'
services:
  entity-central:
    build: 
      context: entity-central
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
    - 8080:8080
  entity-one:
    build:
      context: entity-one
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8081:8080
  entity-two:
    build:
      context: entity-two
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8082:8080